site_name: GameDex
repo_url: https://github.com/xerocuil/gamedex

plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_root_heading: false
            show_source: true
            heading_level: 2
            show_root_toc_entry: false
            show_symbol_type_toc: false

theme:
  name: "material"

nav:
  - Home: readme.md
  - changelog.md
  - Developer Notes: dev_notes/index.md

markdown_extensions:
  - toc:
      toc_depth: "3"
  - pymdownx.tasklist